# ----
# Site

title: Technotes
url: 
baseurl:

theme: jekyll-theme-hacker


# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
# logo: /siteicon.png
description: Technotes by Mangal
author: mangalbhaskar
social:
  name: Technotes Template
  links:
    - https://github.com/mangalbhaskar/technotes


# -----
# Development

# the preview server used. Leave as is.
host: 127.0.0.1

# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.
port: 4004


# -----
# Build

# timezone: Etc/UTC

# permalink: /:categories/:title/

plugins:
  - jekyll-extract-element
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE


highlighter: rouge
# library used for syntax highlighting

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  topics:
    output: false

defaults:
  scope:
    path: ""
    type: "topics"
    # layout: "page"